sudo: false
language: python
python:
  - "2.7"
  - "3.4"
install:
  - "pip install pytest-cov"
  - "pip install coveralls"
  - "pip install -e ."
script: 
  - py.test --cov mapbox --cov-report term-missing
after_success:
  - coveralls
