sudo: false
language: python
python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - pypy
cache:
  directories:
    - $HOME/.pip-cache/
env:
  global:
    - secure: "BbwEk6d/TfwH+wruLQRXIYhw+Q3LxSr7Ons6MTVektfj72uwo9yv4fvXiDp3lJdn+H76/4IgKMm/qfn/WYcjSd0zsEP/7QAVuYmPaxLW0+fSv86o+UjKeHPihL4jwI6FFZEJkdv0X6LYcsIdOCw+RRjy1VJzXZsHenG3r/+c11LmIE8klSxkvK6lXDJbHz7H5FbmZjXte0VicqBxW/y9WJuGJwGykYG9GxiOhnqEsJL8UyLhMryWAgdMmsTRqtC2abQ+groprX28pJOiQp0ONH2CmhegILTjomYY/EjAavTTQfO6kFxmpoalcR2SvpfwBld3suyRhusE0EXMp1K8d9o8Gs95ya5yAV3OJT9MdhautbmTFxTgm5SYHSj9wmkjk9oH2ewZhbaDy7nAXlMby9YPkZdZ30zVMniuoNfCSJuI5XxQw6CbHylFu3obPQpmhVhzPbZhB8iQwQSjRvo+/0otEtrAWAsCNW+tA2zs7A9Nv5YoZJdNpyVjfnnHqL+7Yij572Z41vLtRnmFqb6ZpDz9KFUMrY/WkTadaMD5smao7wWo82TNOZpsX4FzNxMl8RWvoSEZd+1SV7ttEM81pkGNastkxIT4VVgQmsnwO3Y/5RaCDlytTRVWvisBvqVYKnPn6jMBsovirRnDxvymBc5GMqin8FCsiMtVHIMVicA="
install:
  - pip install -U pip --cache-dir $HOME/.pip-cache
  - pip install -e .[test] --cache-dir $HOME/.pip-cache
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install ordereddict; fi
script:
  - py.test --cov mapbox --cov-report term-missing tests/*.py
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 && ! -z "$MAPBOX_ACCESS_TOKEN" ]]; then py.test --doctest-glob='*.md' docs/*.md; fi
after_success:
  - coveralls
deploy:
  on:
    tags: true
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: seang
  password:
    secure: "FpuNoam0Ul8o/Kqtg5YTrTdvuRoE/9oTOsUml0OsapPX1/+qxpaZ7DwbktAQc2Zx1rAAeUkA2MC6rvUW+9xjJAkwS6bUi0NaeZhF2bqP81nprUunnQSTVdXKxHEjcKvLRWfJKB1Oadb1o8zVyoCfLHkbPjrfueJxpjhqfl/If2cHYfrw250Kfg82s9r6mH9iIMtoGOrCrmDITiJQ4juNMRHajHJGsZuQipYICaIUEybiGgpcEsUHsLZrqLPwwUFfCO8ukUHivNlF5HhSpgeAVvgLgXoWFTn6niPpBdr9pCL4ojTvD4O2exEHnfDXTQknvkfYMve9mbhjTxRa1lnri9YqiwpQ/wTaOQTEH5xmxYMH0ZwYUABDDXKPjJa72soYJGHW2uQSnTD079RUYyzOF4xinRKeeA1Dlh8vySvcVZRHrE5/K0WGdEYcAzBLlSgxrHoBMtthBbJFqEGPuHiUucOF1VMGSlcbEJUrHl+AbQNH5bnTXIwgf63Nl7Vuojzu7hKPj/GLRAllqbhFt5MTqiFUesXv96SE3Q1w1wz64MhGAaAGXIk9x67DocYdcufFwBvlMnu5gApanmdJJe2K3ozyGQye0nleOC+qTh9yMZD/Kgvk8Q8myAKwLAVbtAD+hJH5DWWU7wYK6Bw7/5j/JFwbjBBdmTjDtj0KNxqXLCg="
