sudo: false
language: python
python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'
  - pypy
cache:
  directories:
    - $HOME/.pip-cache/
env:
  global:
    - secure: "RrKb6ss6d9e+f5CuadcPjsdY8oQ9zJYdPnNnvgMHknHTr7Xa09v5FrBtQoVowCJLvxzHPd0iQwoXocskZRGYirT+/sJ031hK2aFglxc6p+Z65AzObVU5CyBNKJq17GXQf+ziLbiXBDtpobj0QPmrfLiq0jFIGs+vzxHQ9fpZrPSmGRPkiDXLn0yn6RHGP3twmx27SnlIUbv5xSnhya8srJwo5WyakKDiKwfCPcevhm7uvsaf4S5uzUY6JSrmDScuZZx5m+glUM2mXfzf5S+Lz/r2o00qGh6Dx6xl9JRL5ST/uX3SakR//0RfAO3MAC2P/W8jUpnVKMarGbakoyZk8UigfsiP5vxInGA5qmLlS5ZExe46MK+D2Ea9wVvSbThHeBu8NW7TDpTokJTObIFVCqE/OG+UhQFa2V8KCzit6O8t7+bMSW0PU/uPfl6b3mtgG0LJbfKsAhYPu6XK7U+rJ9c3W0h36HWaENPMVB+V2RfG6Jj1I7VL0VHyJF+KcQq5pvhPQrtCJTuggVAbt3EgS6SDEGrQ3qZO8bd0ImLEiWnzJEogchnKOTD8w2RdJ2wHNRjKM1fH+V4DtyRJmUvq5fox9HNc2imOCeJVjsOZSoQB0rTgqYfnbGy8YV6p3f9X1+deWmxlL7c3v4xxMZQLy4Mf3n1Wvrz0MFYVn4uKRIE="
install:
  - pip install -U pip --cache-dir $HOME/.pip-cache
  - pip install -e .[test] --cache-dir $HOME/.pip-cache
script:
  - py.test --cov mapbox --cov-report term-missing
  - py.test --doctest-glob='docs/*.md' docs/*.md
after_success:
  - coveralls
deploy:
  on:
    tags: true
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: seang
  password:
    secure: FpuNoam0Ul8o/Kqtg5YTrTdvuRoE/9oTOsUml0OsapPX1/+qxpaZ7DwbktAQc2Zx1rAAeUkA2MC6rvUW+9xjJAkwS6bUi0NaeZhF2bqP81nprUunnQSTVdXKxHEjcKvLRWfJKB1Oadb1o8zVyoCfLHkbPjrfueJxpjhqfl/If2cHYfrw250Kfg82s9r6mH9iIMtoGOrCrmDITiJQ4juNMRHajHJGsZuQipYICaIUEybiGgpcEsUHsLZrqLPwwUFfCO8ukUHivNlF5HhSpgeAVvgLgXoWFTn6niPpBdr9pCL4ojTvD4O2exEHnfDXTQknvkfYMve9mbhjTxRa1lnri9YqiwpQ/wTaOQTEH5xmxYMH0ZwYUABDDXKPjJa72soYJGHW2uQSnTD079RUYyzOF4xinRKeeA1Dlh8vySvcVZRHrE5/K0WGdEYcAzBLlSgxrHoBMtthBbJFqEGPuHiUucOF1VMGSlcbEJUrHl+AbQNH5bnTXIwgf63Nl7Vuojzu7hKPj/GLRAllqbhFt5MTqiFUesXv96SE3Q1w1wz64MhGAaAGXIk9x67DocYdcufFwBvlMnu5gApanmdJJe2K3ozyGQye0nleOC+qTh9yMZD/Kgvk8Q8myAKwLAVbtAD+hJH5DWWU7wYK6Bw7/5j/JFwbjBBdmTjDtj0KNxqXLCg=
